This is EDA on the data from the MoneyPuck source.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from pathlib import Path

BASE_PATH = Path(r"..\data\MoneyPuck\raw")

In [7]:
def ffn_from_params(params):
    fpath = os.path.join(BASE_PATH, params["year"], params["season"])
    ffn = os.path.join(fpath, f"{params["category"]}.csv")
    return ffn

## Begin by investigating a single file (skater)

In [19]:
params = {
    "year": "2024",
    "season": "regular",
    "category": "skaters"
    }

ffn = ffn_from_params(params)

df = pd.read_csv(ffn)
print(df.info())
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Columns: 154 entries, playerId to fenwickAgainstAfterShifts
dtypes: float64(147), int64(3), str(4)
memory usage: 5.4 MB
None

,playerId,season,name,team,position,situation,games_played,icetime,shifts,gameScore,...,OffIce_F_xGoals,OffIce_A_xGoals,OffIce_F_shotAttempts,OffIce_A_shotAttempts,xGoalsForAfterShifts,xGoalsAgainstAfterShifts,corsiForAfterShifts,corsiAgainstAfterShifts,fenwickForAfterShifts,fenwickAgainstAfterShifts
0,8478047,2024,Michael Bunting,NSH,L,other,76,2237.0,37.0,26.19,...,7.28,10.09,72.0,87.0,0.00,0.00,0.0,0.0,0.0,0.0
1,8478047,2024,Michael Bunting,NSH,L,all,76,70819.0,1474.0,43.70,...,161.54,187.75,3221.0,3522.0,0.00,0.00,0.0,0.0,0.0,0.0
2,8478047,2024,Michael Bunting,NSH,L,5on5,76,59813.0,1294.0,43.70,...,112.73,122.08,2661.0,2707.0,0.71,1.71,19.0,43.0,16.0,31.0
3,8478047,2024,Michael Bunting,NSH,L,4on5,76,6.0,2.0,2.58,...,0.20,0.17,4.0,11.0,0.00,0.00,0.0,0.0,0.0,0.0
4,8478047,2024,Michael Bunting,NSH,L,5on4,76,8763.0,141.0,36.88,...,23.81,2.60,311.0,54.0,0.00,0.01,0.0,1.0,0.0,1.0

In [21]:
list(df.columns)

['playerId',
 'season',
 'name',
 'team',
 'position',
 'situation',
 'games_played',
 'icetime',
 'shifts',
 'gameScore',
 'onIce_xGoalsPercentage',
 'offIce_xGoalsPercentage',
 'onIce_corsiPercentage',
 'offIce_corsiPercentage',
 'onIce_fenwickPercentage',
 'offIce_fenwickPercentage',
 'iceTimeRank',
 'I_F_xOnGoal',
 'I_F_xGoals',
 'I_F_xRebounds',
 'I_F_xFreeze',
 'I_F_xPlayStopped',
 'I_F_xPlayContinuedInZone',
 'I_F_xPlayContinuedOutsideZone',
 'I_F_flurryAdjustedxGoals',
 'I_F_scoreVenueAdjustedxGoals',
 'I_F_flurryScoreVenueAdjustedxGoals',
 'I_F_primaryAssists',
 'I_F_secondaryAssists',
 'I_F_shotsOnGoal',
 'I_F_missedShots',
 'I_F_blockedShotAttempts',
 'I_F_shotAttempts',
 'I_F_points',
 'I_F_goals',
 'I_F_rebounds',
 'I_F_reboundGoals',
 'I_F_freeze',
 'I_F_playStopped',
 'I_F_playContinuedInZone',
 'I_F_playContinuedOutsideZone',
 'I_F_savedShotsOnGoal',
 'I_F_savedUnblockedShotAttempts',
 'penalties',
 'I_F_penalityMinutes',
 'I_F_faceOffsWon',
 'I_F_hits',
 'I_F_takeaways',
 'I_F_giveaways',
 'I_F_lowDangerShots',
 'I_F_mediumDangerShots',
 'I_F_highDangerShots',
 'I_F_lowDangerxGoals',
 'I_F_mediumDangerxGoals',
 'I_F_highDangerxGoals',
 'I_F_lowDangerGoals',
 'I_F_mediumDangerGoals',
 'I_F_highDangerGoals',
 'I_F_scoreAdjustedShotsAttempts',
 'I_F_unblockedShotAttempts',
 'I_F_scoreAdjustedUnblockedShotAttempts',
 'I_F_dZoneGiveaways',
 'I_F_xGoalsFromxReboundsOfShots',
 'I_F_xGoalsFromActualReboundsOfShots',
 'I_F_reboundxGoals',
 'I_F_xGoals_with_earned_rebounds',
 'I_F_xGoals_with_earned_rebounds_scoreAdjusted',
 'I_F_xGoals_with_earned_rebounds_scoreFlurryAdjusted',
 'I_F_shifts',
 'I_F_oZoneShiftStarts',
 'I_F_dZoneShiftStarts',
 'I_F_neutralZoneShiftStarts',
 'I_F_flyShiftStarts',
 'I_F_oZoneShiftEnds',
 'I_F_dZoneShiftEnds',
 'I_F_neutralZoneShiftEnds',
 'I_F_flyShiftEnds',
 'faceoffsWon',
 'faceoffsLost',
 'timeOnBench',
 'penalityMinutes',
 'penalityMinutesDrawn',
 'penaltiesDrawn',
 'shotsBlockedByPlayer',
 'OnIce_F_xOnGoal',
 'OnIce_F_xGoals',
 'OnIce_F_flurryAdjustedxGoals',
 'OnIce_F_scoreVenueAdjustedxGoals',
 'OnIce_F_flurryScoreVenueAdjustedxGoals',
 'OnIce_F_shotsOnGoal',
 'OnIce_F_missedShots',
 'OnIce_F_blockedShotAttempts',
 'OnIce_F_shotAttempts',
 'OnIce_F_goals',
 'OnIce_F_rebounds',
 'OnIce_F_reboundGoals',
 'OnIce_F_lowDangerShots',
 'OnIce_F_mediumDangerShots',
 'OnIce_F_highDangerShots',
 'OnIce_F_lowDangerxGoals',
 'OnIce_F_mediumDangerxGoals',
 'OnIce_F_highDangerxGoals',
 'OnIce_F_lowDangerGoals',
 'OnIce_F_mediumDangerGoals',
 'OnIce_F_highDangerGoals',
 'OnIce_F_scoreAdjustedShotsAttempts',
 'OnIce_F_unblockedShotAttempts',
 'OnIce_F_scoreAdjustedUnblockedShotAttempts',
 'OnIce_F_xGoalsFromxReboundsOfShots',
 'OnIce_F_xGoalsFromActualReboundsOfShots',
 'OnIce_F_reboundxGoals',
 'OnIce_F_xGoals_with_earned_rebounds',
 'OnIce_F_xGoals_with_earned_rebounds_scoreAdjusted',
 'OnIce_F_xGoals_with_earned_rebounds_scoreFlurryAdjusted',
 'OnIce_A_xOnGoal',
 'OnIce_A_xGoals',
 'OnIce_A_flurryAdjustedxGoals',
 'OnIce_A_scoreVenueAdjustedxGoals',
 'OnIce_A_flurryScoreVenueAdjustedxGoals',
 'OnIce_A_shotsOnGoal',
 'OnIce_A_missedShots',
 'OnIce_A_blockedShotAttempts',
 'OnIce_A_shotAttempts',
 'OnIce_A_goals',
 'OnIce_A_rebounds',
 'OnIce_A_reboundGoals',
 'OnIce_A_lowDangerShots',
 'OnIce_A_mediumDangerShots',
 'OnIce_A_highDangerShots',
 'OnIce_A_lowDangerxGoals',
 'OnIce_A_mediumDangerxGoals',
 'OnIce_A_highDangerxGoals',
 'OnIce_A_lowDangerGoals',
 'OnIce_A_mediumDangerGoals',
 'OnIce_A_highDangerGoals',
 'OnIce_A_scoreAdjustedShotsAttempts',
 'OnIce_A_unblockedShotAttempts',
 'OnIce_A_scoreAdjustedUnblockedShotAttempts',
 'OnIce_A_xGoalsFromxReboundsOfShots',
 'OnIce_A_xGoalsFromActualReboundsOfShots',
 'OnIce_A_reboundxGoals',
 'OnIce_A_xGoals_with_earned_rebounds',
 'OnIce_A_xGoals_with_earned_rebounds_scoreAdjusted',
 'OnIce_A_xGoals_with_earned_rebounds_scoreFlurryAdjusted',
 'OffIce_F_xGoals',
 'OffIce_A_xGoals',
 'OffIce_F_shotAttempts',
 'OffIce_A_shotAttempts',
 'xGoalsForAfterShifts',
 'xGoalsAgainstAfterShifts',
 'corsiForAfterShifts',
 'corsiAgainstAfterShifts',
 'fenwickForAfterShifts',
 'fenwickAgainstAfterShifts']

For general analyses, can narrow down the scenarios just to the "all" situation.

In [28]:
df = df[df["situation"]=='all']

df.iloc[0]['I_F_goals']

np.float64(19.0)

## What about if a player is traded during a season?

In [30]:
df[df["playerId"]==	8478047]

,playerId,season,name,team,position,situation,games_played,icetime,shifts,gameScore,...,OffIce_F_xGoals,OffIce_A_xGoals,OffIce_F_shotAttempts,OffIce_A_shotAttempts,xGoalsForAfterShifts,xGoalsAgainstAfterShifts,corsiForAfterShifts,corsiAgainstAfterShifts,fenwickForAfterShifts,fenwickAgainstAfterShifts
1,8478047,2024,Michael Bunting,NSH,L,all,76,70819.0,1474.0,43.7,...,161.54,187.75,3221.0,3522.0,0.0,0.0,0.0,0.0,0.0,0.0

It would appear all the stats are for at the end of the season. Michael Bunting in 2024 played for PIT and NSH, but the above shows all of the stats under one row. Therefore there could be some innaccurate data throughout.

## How many players are in the dataset for a given season?

In [39]:
print(df.shape)
print(df['playerId'].unique().shape)

(920, 154)
(920,)

This would suggest that there are not duplicate rows.

## Does I_F_points = I_F_goals + I_F_primaryAssists + I_F_secondaryAssists

In [47]:
mask = (df['I_F_goals'] + df['I_F_primaryAssists'] + df['I_F_secondaryAssists'] ) == df['I_F_points']
sum(mask)

920

Yes it does.

## Investigate a single file (goalie)

In [49]:
params = {
    "year": "2024",
    "season": "regular",
    "category": "goalies"
    }

ffn = ffn_from_params(params)

df = pd.read_csv(ffn)
print(df.info())
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 515 entries, 0 to 514
Data columns (total 36 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   playerId                   515 non-null    int64
 1   season                     515 non-null    int64
 2   name                       515 non-null    str
 3   team                       515 non-null    str
 4   position                   515 non-null    str
 5   situation                  515 non-null    str
 6   games_played               515 non-null    int64
 7   icetime                    515 non-null    float64
 8   xGoals                     515 non-null    float64
 9   goals                      515 non-null    float64
 10  unblocked_shot_attempts    515 non-null    float64
 11  xRebounds                  515 non-null    float64
 12  rebounds                   515 non-null    float64
 13  xFreeze                    515 non-null    float64
 14  freeze                     515 non-null    float64
 15  xOnGoal                    515 non-null    float64
 16  ongoal                     515 non-null    float64
 17  xPlayStopped               515 non-null    float64
 18  playStopped                515 non-null    float64
 19  xPlayContinuedInZone       515 non-null    float64
 20  playContinuedInZone        515 non-null    float64
 21  xPlayContinuedOutsideZone  515 non-null    float64
 22  playContinuedOutsideZone   515 non-null    float64
 23  flurryAdjustedxGoals       515 non-null    float64
 24  lowDangerShots             515 non-null    float64
 25  mediumDangerShots          515 non-null    float64
 26  highDangerShots            515 non-null    float64
 27  lowDangerxGoals            515 non-null    float64
 28  mediumDangerxGoals         515 non-null    float64
 29  highDangerxGoals           515 non-null    float64
 30  lowDangerGoals             515 non-null    float64
 31  mediumDangerGoals          515 non-null    float64
 32  highDangerGoals            515 non-null    float64
 33  blocked_shot_attempts      515 non-null    float64
 34  penalityMinutes            515 non-null    float64
 35  penalties                  515 non-null    float64
dtypes: float64(29), int64(3), str(4)
memory usage: 145.0 KB
None

,playerId,season,name,team,position,situation,games_played,icetime,xGoals,goals,...,highDangerShots,lowDangerxGoals,mediumDangerxGoals,highDangerxGoals,lowDangerGoals,mediumDangerGoals,highDangerGoals,blocked_shot_attempts,penalityMinutes,penalties
0,8478048,2024,Igor Shesterkin,NYR,G,other,61,4629.0,14.02,13.0,...,21.0,2.38,3.81,7.83,4.0,1.0,8.0,29.0,0.0,0.0
1,8478048,2024,Igor Shesterkin,NYR,G,all,61,210308.0,188.56,167.0,...,228.0,52.99,64.10,71.46,56.0,64.0,47.0,979.0,6.0,3.0
2,8478048,2024,Igor Shesterkin,NYR,G,5on5,61,172568.0,133.92,118.0,...,149.0,43.40,49.14,41.39,46.0,52.0,20.0,816.0,4.0,2.0
3,8478048,2024,Igor Shesterkin,NYR,G,4on5,61,18561.0,36.41,31.0,...,54.0,6.04,9.75,20.63,4.0,9.0,18.0,119.0,2.0,1.0
4,8478048,2024,Igor Shesterkin,NYR,G,5on4,61,14550.0,4.16,5.0,...,4.0,1.14,1.41,1.60,2.0,2.0,1.0,15.0,0.0,0.0

In [50]:
list(df.columns)

['playerId',
 'season',
 'name',
 'team',
 'position',
 'situation',
 'games_played',
 'icetime',
 'xGoals',
 'goals',
 'unblocked_shot_attempts',
 'xRebounds',
 'rebounds',
 'xFreeze',
 'freeze',
 'xOnGoal',
 'ongoal',
 'xPlayStopped',
 'playStopped',
 'xPlayContinuedInZone',
 'playContinuedInZone',
 'xPlayContinuedOutsideZone',
 'playContinuedOutsideZone',
 'flurryAdjustedxGoals',
 'lowDangerShots',
 'mediumDangerShots',
 'highDangerShots',
 'lowDangerxGoals',
 'mediumDangerxGoals',
 'highDangerxGoals',
 'lowDangerGoals',
 'mediumDangerGoals',
 'highDangerGoals',
 'blocked_shot_attempts',
 'penalityMinutes',
 'penalties']

# What columns are we actually interested in?

For simple analyses:

## Skaters
- playerId
- season
- situation == "all"
- games_played
- I_F_goals
- I_F_points (Goals + Assists)
- I_F_primaryAssists
- I_F_secondaryAssists

## Goalies