# 02_EDA.ipynb

Take a preliminary look at the NHL API data.

Data must be downloaded to run script, see repo root README.md for download information.

# games.csv

Contains the score for games

In [1]:
from nhl_pool.config import PROCESSED_DIR
import pandas as pd

games = pd.read_csv(PROCESSED_DIR / "games.csv")
print(games.info())
games.head()

<class 'pandas.DataFrame'>
RangeIndex: 14087 entries, 0 to 14086
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gameId          14087 non-null  int64
 1   gameType        14087 non-null  int64
 2   gameDate        14087 non-null  str
 3   gameState       14087 non-null  str
 4   awayTeamId      14087 non-null  int64
 5   awayTeamAbbrev  14087 non-null  str
 6   awayTeamScore   14085 non-null  float64
 7   homeTeamId      14087 non-null  int64
 8   homeTeamAbbrev  14087 non-null  str
 9   homeTeamScore   14085 non-null  float64
 10  lastPeriodType  14085 non-null  str
 11  sourceFile      14087 non-null  str
dtypes: float64(2), int64(4), str(6)
memory usage: 1.3 MB
None

,gameId,gameType,gameDate,gameState,awayTeamId,awayTeamAbbrev,awayTeamScore,homeTeamId,homeTeamAbbrev,homeTeamScore,lastPeriodType,sourceFile
0,2015010001,1,2015-09-20,FINAL,1,NJD,0.0,6,BOS,2.0,REG,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
1,2015010002,1,2015-09-20,FINAL,13,FLA,2.0,18,NSH,5.0,REG,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
2,2015010003,1,2015-09-20,FINAL,13,FLA,3.0,18,NSH,2.0,OT,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
3,2015010004,1,2015-09-21,FINAL,26,LAK,5.0,53,ARI,1.0,REG,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
4,2015010005,1,2015-09-21,FINAL,22,EDM,3.0,20,CGY,1.0,REG,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...

# skaters.csv

In [2]:
from nhl_pool.config import PROCESSED_DIR
import pandas as pd

def stats_file_path(params):
    return PROCESSED_DIR / str(params["season"]) / params["season_type"] / f"{params["player_type"]}.csv"

In [3]:
params = {
    "season": 20242025,
    "season_type": "regular",
    "player_type": "skaters"
}

path = stats_file_path(params)
skaters = pd.read_csv(path)
print(skaters.info())
skaters.head()

<class 'pandas.DataFrame'>
RangeIndex: 1027 entries, 0 to 1026
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   playerId             1027 non-null   int64
 1   firstName            1027 non-null   str
 2   lastName             1027 non-null   str
 3   teamAbbrev           1027 non-null   str
 4   season               1027 non-null   int64
 5   seasonType           1027 non-null   int64
 6   positionCode         1027 non-null   str
 7   gamesPlayed          1027 non-null   int64
 8   goals                1027 non-null   int64
 9   assists              1027 non-null   int64
 10  points               1027 non-null   int64
 11  plusMinus            1027 non-null   int64
 12  penaltyMinutes       1027 non-null   int64
 13  powerPlayGoals       1027 non-null   int64
 14  shorthandedGoals     1027 non-null   int64
 15  gameWinningGoals     1027 non-null   int64
 16  overtimeGoals        1027 non-null   int64
 17  shots                1027 non-null   int64
 18  shootingPctg         1027 non-null   float64
 19  avgTimeOnIcePerGame  1027 non-null   float64
 20  avgShiftsPerGame     1027 non-null   float64
 21  faceoffWinPctg       1027 non-null   float64
 22  sourceFile           1027 non-null   str
dtypes: float64(4), int64(14), str(5)
memory usage: 184.7 KB
None

,playerId,firstName,lastName,teamAbbrev,season,seasonType,positionCode,gamesPlayed,goals,assists,...,powerPlayGoals,shorthandedGoals,gameWinningGoals,overtimeGoals,shots,shootingPctg,avgTimeOnIcePerGame,avgShiftsPerGame,faceoffWinPctg,sourceFile
0,8473986,Alex,Killorn,ANA,20242025,2,L,82,19,18,...,0,1,5,1,134,0.141791,1036.5610,21.6585,0.380952,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
1,8475208,Brian,Dumoulin,ANA,20242025,2,D,61,2,14,...,0,0,0,0,57,0.035088,1187.5410,25.0328,0.000000,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
2,8475462,Radko,Gudas,ANA,20242025,2,D,81,1,15,...,0,0,0,0,89,0.011236,1191.9383,23.9012,0.000000,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
3,8475764,Cam,Fowler,ANA,20242025,2,D,17,0,4,...,0,0,0,0,17,0.000000,1263.7059,25.8235,0.000000,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
4,8476458,Ryan,Strome,ANA,20242025,2,C,82,10,31,...,0,0,3,0,137,0.072993,1000.9634,20.6707,0.416803,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...

## How many players show up more than once?
Players could exist more than once due to trades.

In [4]:
id_counts = skaters['playerId'].value_counts()

len(id_counts[id_counts > 1].index.tolist())

102

## What are the different positions?

In [5]:
skaters["positionCode"].value_counts()

positionCode
D    357
C    323
L    181
R    166
Name: count, dtype: int64

There aren't any cases where players play more than one position, probably just goes off their officially listed position.

# goalies.csv

In [6]:
params = {
    "season": 20242025,
    "season_type": "regular",
    "player_type": "goalies"
}

path = stats_file_path(params)
goalies = pd.read_csv(path)
print(goalies.info())
goalies.head()

<class 'pandas.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   playerId             112 non-null    int64
 1   firstName            112 non-null    str
 2   lastName             112 non-null    str
 3   teamAbbrev           112 non-null    str
 4   season               112 non-null    int64
 5   seasonType           112 non-null    int64
 6   positionCode         112 non-null    str
 7   gamesPlayed          112 non-null    int64
 8   gamesStarted         112 non-null    int64
 9   wins                 112 non-null    int64
 10  losses               112 non-null    int64
 11  overtimeLosses       112 non-null    int64
 12  goalsAgainstAverage  112 non-null    float64
 13  savePercentage       112 non-null    float64
 14  shotsAgainst         112 non-null    int64
 15  saves                112 non-null    int64
 16  goalsAgainst         112 non-null    int64
 17  shutouts             112 non-null    int64
 18  goals                112 non-null    int64
 19  assists              112 non-null    int64
 20  points               112 non-null    int64
 21  penaltyMinutes       112 non-null    int64
 22  timeOnIce            112 non-null    int64
 23  sourceFile           112 non-null    str
dtypes: float64(2), int64(17), str(5)
memory usage: 21.1 KB
None

,playerId,firstName,lastName,teamAbbrev,season,seasonType,positionCode,gamesPlayed,gamesStarted,wins,...,shotsAgainst,saves,goalsAgainst,shutouts,goals,assists,points,penaltyMinutes,timeOnIce,sourceFile
0,8473503,James,Reimer,ANA,20242025,2,G,2,2,0,...,66,57,9,0,0,0,0,0,7200,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
1,8476434,John,Gibson,ANA,20242025,2,G,29,28,11,...,811,740,72,0,0,1,1,4,93729,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
2,8478024,Ville,Husso,ANA,20242025,2,G,4,3,1,...,134,124,10,0,0,0,0,0,12057,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
3,8480843,Lukas,Dostal,ANA,20242025,2,G,54,49,23,...,1625,1467,158,1,0,0,0,0,183459,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
4,8476914,Joonas,Korpisalo,BOS,20242025,2,G,27,24,11,...,693,619,74,3,0,0,0,0,91782,B:\repos\nhl-playoff-pool-optimizer\data\raw\2...

In [8]:
goalies.columns

Index(['playerId', 'firstName', 'lastName', 'teamAbbrev', 'season',
       'seasonType', 'positionCode', 'gamesPlayed', 'gamesStarted', 'wins',
       'losses', 'overtimeLosses', 'goalsAgainstAverage', 'savePercentage',
       'shotsAgainst', 'saves', 'goalsAgainst', 'shutouts', 'goals', 'assists',
       'points', 'penaltyMinutes', 'timeOnIce', 'sourceFile'],
      dtype='str')

## How is goalsAgainstAverage computed?

In [15]:
7200/60

120.0

In [18]:
g = goalies.iloc[2]
g

playerId                                                         8478024
firstName                                                          Ville
lastName                                                           Husso
teamAbbrev                                                           ANA
season                                                          20242025
seasonType                                                             2
positionCode                                                           G
gamesPlayed                                                            4
gamesStarted                                                           3
wins                                                                   1
losses                                                                 1
overtimeLosses                                                         1
goalsAgainstAverage                                             2.985817
savePercentage                                                  0.925373
shotsAgainst                                                         134
saves                                                                124
goalsAgainst                                                          10
shutouts                                                               0
goals                                                                  0
assists                                                                0
points                                                                 0
penaltyMinutes                                                         0
timeOnIce                                                          12057
sourceFile             B:\repos\nhl-playoff-pool-optimizer\data\raw\2...
Name: 2, dtype: object

timeOnIce is in seconds

In [19]:
g["goalsAgainst"] * 60 / (g["timeOnIce"] / 60)

np.float64(2.9858173675043544)